apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hanica
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: hanica tenant — web app and workers
  sourceRepos:
    - https://github.com/tayzar-tznw/gke-argocd.git
  destinations:
    - namespace: hanica
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "gateway.networking.k8s.io"
      kind: "*"
    - group: "autoscaling"
      kind: "*"
    - group: "keda.sh"
      kind: "*"
  orphanedResources:
    warn: true
